name: kumvent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.23

environment:
  sdk: ">=2.16.1"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_credit_card:
  flutter_screenutil:
  font_awesome_flutter:
  google_fonts:
  lints:
  progress_indicators:
  firebase_core:
  firebase_auth:
  firebase_dynamic_links:
  fluttertoast:
  cloud_firestore:
  shared_preferences:
  flutter_slidable:
  firebase_core_platform_interface:
  firebase_messaging:

  gameball:
    git:
      url: https://github.com/t-bolt/gameball.git

dev_dependencies:

  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - google_fonts/
